title: Sxg, I see
description: >
    Just for coding.
timezone: Asia/Shanghai
url: 'https://www.sxgic.com'

email: geekpanshi@gmail.com
baseurl: ""

twitter_username: geekpanshi
github_username:  xingangshi

repository: sxgic/sxgic.github.io

include:
  - CNAME

plugins:
  - jekyll-org
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
